import 'package:flutter/material.dart';

final List<String> pictures=['assets/images/economic.jpg','assets/images/genius.jpg','assets/images/health.jpg','assets/images/techno.jpg','assets/images/food_and_drink.jpg'];


final List<String> economical_hacks=[
  'Use the library instead of the bookstore','AAA insurance will pick anyone up and drive them home for free on New Years Eve',
  'Accidentally_get deodorant on your shirt when putting it on? Rub a dryer sheet on it to take it off!',
  'According to TSA rules, you can get drinks through airport securtiy if they are frozen solid',
  'Along with budgeting, make sure you track your spending so you know how much is going out and coming in each month',
  'Always order papa johns pizza online. The code 250FF works every time for 25% off your order',
  'Always take a look at the floor near the bar.Drunk people always drop their money!',
  'American quarters with the year 1965 and older on them are now worth \$4.20 and their value will only go up!',
  'As hard as it may be, establish eye contact with everyone you meet.It\'s one of the best ways to make people take you seriously',
  'At Chegg.com you can rent expensive textbooks online for a semester instead of buying the all at a bookstore.',
  'At Chipotle, there is no limit to the number of tortillas you can order on the side',
  'Buy condoms online instead of in a supermarket or drug store.They are WAY cheaper',
  'Candles will burn longer and drip less if they are placed in the freezer for a few hours before using.',
  'Cheapfree50.com is a site that offers Nike shoes at 50% off!',
  'Clear all debts as soon as possible. You will save hundreds of thousands on interest',
  'Clear out an old lotion bottle for you beach bag and put your phone,money and keys in it for safer keeping at the beach',
  'Close with the neighbours in the dorm next to you? Share your wifi and split the bill',
  'Cut back on Oreas.A new study shows they are just as addictive as cocaine',
  'Cutting through aluminum foil will sharpen your knives',
  'Don\'t buy new ink cartidges, takes old ones to Castco get them filled for only \$10!',
  'Each 5 mph you drive over 60 mph is like paying an additional 10 cents a gallon for gas.'
];


final List<String> food_and_drink=[
  'Add one teaspon of lemon juice to each quart of water when cooking rice, this will keep rice fluffy',
  'At a restaurant, you\'ll never go wrong ordering the chef\'s favorite dish.',
  'Banana is a happy fruit. Eating just one can help relieve emotions, anger and or depression',
  'Butter too hard or frozen to spread? Grap acheese grater and grate it right onto the bread.Works like charm!',
  'Buy bananas in various degrees of ripeness,so that you will have a ripe one to eat every day.',
  'Caramel Apple slices: Hollow out half an apple, pour caramel in,let harden in the freezer, cut into slices,enjoy!',
  'Coffee has been found to reverse liver damage caused by alcohol',
  'Crush up Oreo cookies and put them in a salt grinder for an easy and tasty dessert toppings',
  'Drinking chocolate milk has been proven to help relieve muscle soreness after a workout.',
  'Eating Salmon can help you hair grow faster',
  'Eating bananas at the time of conception increases the chances of having a baby boy.',
  'Eating mangoes before smoking marijuana can heighten it\'s effects!',
  'Eating watermelon can help reduce ocne breakouts and keep skin Health & Fitnessier',
  'Hate that dust in the last couple bowls of cereal?Pour it into  a strainer first',
  'Honey is the only food that will never rot.A jar of honey can remain edible for over 3,000 years',
  'Honey, when mixed with vineger and water can remove worms and other parasites in you body',
  'if no jelly is available for a PB & J, use  maple syrup instead. Just as delicious.',
  'if you peel a banana from the bottom, you won\'t have to pick the little  strings things off of it.',
  'Keep bananas fresher longer by wrapping the stems in plastic wrap',
  'Make \'cookie bowls \' by simply turning your muffin or cupcake pan upside down',
  'Microwave a Nature Valley  bar for 30 seconds to prevent crumbs when you eat it',
  'Mix vodka + candy in a container. Wait a day, then get drunk while snacking!',
  'Mountain Dew was origionally made to be mixed with whiskey.Try it!',
  'Nuttella + milk in the microwave will give you the best chocolate ever!'];


final List<String> genius=[
  'Get invited to wedding? Set the date as a recurring event  in your chance in your calender. So you can wish them a happy anniversary every year',
  'Study your notes whithin one day of taking them.Retention rates are 60% higher then!',
  'A high GPA looks good on paper, but networking and building friendsships is what gets you a jop',
  'Aperson usually makes alot of hand gestures when telling a true story. When telling a lie a person hands will stay noticeably still',
  'Always check your  your cell signal when looking for new apartments or dorms to live in',
  'An old CD spindle makes for the perfect bagel holder.They are great for packing  lunches',
  'At a restaurant? wash your hands after ordering.The menu is generally the dirtiest thing you can touch',
  'Before he even speaks,the way a man stands (slouching or not) accunts for 80* of women\'s frist impression',
  'Boiling water before freezing it will give you crsytal clear ice.',
  'Buy world map shower curtain. you will become a geograph expert from all the time you  spend in the bathroom!',
  'Create a phone contact called  \'ignore \' and make the ring tone of that contact silent Add in whoever you  don\'t want to talk to ',
  'Deodorant on an insect bite or other itchy site will stop the itch',
  'Don\'t have a coin to flip? Look at the time. If it\'s even,heads.If it\'s odd, tails',
  'Eating chocolate while studing math can improve you math skills',
  'Eating mangoes before smoking marijuana can heighten it\'s effects',
  'Ever wonder why phone cards are so short? Using your phone while it is charging can damage the battery',
  'Fold your receipt around the gift card to always know your balance',
  'Fours words to get free alcohol at a party I\'ve never been drunk',
  'Get a puppy before  you decide to have children',
  'Get a study partner with blue eyes. Studies show that blue-eyed individuals study more effectively and tend to perform better on exams ',
  'Getting a call from a telemarketer? Don\'t say anything. Just press \'9\' on your phone.it will add your number to the don\'t call list ',
  'Going to a bar? Start by giving the bartender a \$ tip. You will get amaxing service the rest of the night',
  'Going to the  beach? Put your phone in a sandwich bag and you will stiil be able to use the touch screen!',
  'Grocer stores stack their product by sell-by date, wich means the oldest food\'s in the front. Grab the fresh food in the back!',
  'If someone is tailgating you turn on your windshield wiper fluid. it will fly back and squirt them.'];

final List<String> health=[
  'Popcorn has more antioxidants than fruits and vegetable! it is most healthy when air-popped.Avoid adding oil or butter',
  '1 apple a day - No doctor, 1 Tulsi leaf a day -No cancer , 1 lemon a day - No Fat',
  '10 people die every minute from a tobacco-related disease',
  '2 ounces of wheatgrass is the equivalent  to eating 4 pounds of green vegetables.',
  '30% gym,70% diet,Abs are made in the kitchen,not in the gym.',
  '40% of your  overall happiness depends  on your  internal state of mind. Be positeve!'
  'A chemical called oxytocin is released when people cuddle which helps to heal physical wounds.'
  'A cure for headaches,Take alime, cut it in half, and rub it on your forehead.The throbbing should go away',
  'A glass of beet juice a day for a few weeks is especially useful for teenages, because it helps to control the overproduction of hormones.',
  'A good  anti-aging diet should consist of 50% vegetables, 20% protein, 20% fruits, adn 10% grains.',
  'A high intake of added sugar is linded to numerous diseases, including obesity,type 2 diabetes,heart disease and many forms of cancer.',
  'A new 2017 study has realffirmed, the more time you spend on Facebook, the worse you feel about yourself',
  'A new study of over 1 million people finds that one hour of physical activity per day could offset health risk of 8 hours of sitting.',
  'A tablespoon of apple cider binegar relieves allergy and asthma symptoms.'
  'A tasty and easy source to access a variety of important vitamins is multivitamin gummy sweeets.',
  'According to a study, smelling rubbing alcohol can relieve nausea almost instantly.',
  'According to the largest study ever done on marijuana, smoking it once or twice  a week is not bad for your lungs.',
  'Add some splice to your foods. Spices contain Capsaicin,with speeds up your metabolism for a couple hours after you eat.',
  'Add wheat germ or flaxseeds to your yogurt.Wheat germ is packed with vitamin E and flaxseeds have high levels of Omega-3',
  'Adding vodka to your shampo can strengthen your hair, prevent dry scalp, and stop dandruff',
  'Alcohol is 2-3 times more potent when you drink it while flying',
  'Almonds are an excellent source of energy as well as neutrents.',
  'Avoid eating raw or undercooked meats of any type.',
  'Avoid heavy meals in the summer months,especially during hot days.',
  'Avoid sity-ups with anchored feet, which can hurt your lower back.',
  'Avoid sunburns and sun exposure by using adequate skin protection; use brimmed hats, protective clothing, and sunscreen'
];

final List<String> life_tips=[
  '5 simple rules to be happy:Free your heart from hatred.Free your mind from worries.Live simply.Give more.Expect less.',
'A study found that aggressive music,like heavy metal, can make the listener feel inspired and can help regulate emotions',
'Accidentially text the wrong person? immediatly put your phone on airplane mode and once it fails to deliver,delete the message',
'According to a study, Kids as young as 4 years old just want to be friends with other kids who know the same songs they do ',
'Actions prove who someone is, words prove who they want tobe',
'Admit it when you are wrong and shut up when you are right.This is a simple way to drastically imporve the quality of your relationships',
'After someone has a baby, stop their Facebook posts from showing up in your newsfeed,',
'Always be honest so when you have to lie,people will believe you',
'Always be ten mimutes early to everything.After a while,it will become a habit and you will never be late to any thing agian',
'Always go out in public dressed like you are about to meet the love of your life',
'Angry? Take a deep breath before you speak ,becouse you mouth acts quicker than your brain',
'AS general rule, any club that pats you down before you enter should\'t be a place you should hang out at.',
'ASparagus is also another proven method to cure a hangover',
'Avoid people who make you feel quilty about not being able to help them out. You do not have to be everyone\'s hero',
'Be sure you find a pet with a great personality, who interacts with you and makes you laugh for maximum immune-boosting benefits',
'Boiling water before freezing it will give you crystal clear ice',
'Buy a yelp shirt and wear it to restaurants, you will get the best service',
'By peeing in the shower, you can save about, 1,157 gallons of water a year!',
'By raising you legs slowly and lying on you back, you cannot sink into quicksand',
'Call, ro at a minimum, text your friecs on their birthdays. Don\'t just give them a Facebook comment',
'Can\'t brush after a meal? Gargle salt water. You will be amazed what comes out of your mouth!',
'Crying releases extra stress hormones, which is why you feel better after',
'Depressed? Do something really nice for someone else.Trust me it helps',
'Did you know that crayons can be used as candles? They achually burn up to 30 minutes',
'Don\'t compare your chapter 1 to someone else\'s chapter',
'Don\'t keep all your weird shit in one drawer.'];

final List<String> techno=['if you find locked iphone and siri is still enabled, ask \'who do you belong to?\' to see the owner\'s contact information',
'10 minutesmail.com gives you a fake email address so you don\'t have to use your own personal email address when signing up for things',
'A lot of automated answering systems are programmed to recognize swearing, and dropping an F-bomb or two can get you right to a human',
'Accidentally erase something you just typed on your iphone? To undo that,just shake it!',
'An iPad charger will charge you iPhone much faster',
'Before going to a suspicious site,Google safebrowsing(website) to see a ninety-day history of malware attempts on its visitors',
'Better Explained tough math concepts in better and intuitve way',
'Break something? FicintClub.com will show you step by step how to fix just about anything.',
'By charging your laptop battery only up to 80% instead of 100% you can greatly extend the usable lifespan of the battery.',
'CMD.fm is a site tha allows you to listen to any genre of music with unlimited skips for free.',
'Can\'t afford Microsoft office? Download open office . it is free and has more featues ',
'Can\'t finish your assignment before deadline? Corrupt-a-file.net corrupst your assignment files so that you can ask for extra time.',
'Change the lock screen on your phone to a picture of you name and contact info. That way if ou lose it, the finder can easily see whose phone it is and how to get the pnone back to you',
'Command+shift+3 takes a screenshot on MacBooks.',
'Cut your pack of bacon in half for easier baking , cleaner storage, and better size for sandwich filling',
'Dial the French button when calling customer support. They always speak good English and you will not have to wait',
'Documentry Heaven.com is , well ,a documentary heaven.',
'FillerDeals.com is similar to ThislsWhymBroke.com but everything is under\$15',
'Fix a scratched CD or DVD by rubbing a peeled banana on it and then buffing it out with the outside of the peel',
'For amazon, use camelcamelcamel.com to get alerts when prices drop',
'For the best sound in a movie theater, sit 2/3 of the way back adn as close to the middle as possible, this is where the audio engineer sits when they do the final mix.',
'Forgot an assignment and need to email it? change the date on your computer system and send it ',
'Forgot where you park your car? Don\'t worry, Google Now remembers.'];
var allhacks_length=food_and_drink.length+genius.length+economical_hacks.length+health.length+life_tips.length;
var allhacks=new List(allhacks_length);

